### ISSUE TITLE
Buffer.concat in Encoder.prototype._transform

### ISSUE THREAD

**Issue by davedoesdev** [rkusa/frame-stream#4]
I think it's better to push each buffer separately. i.e. rather than this:

```javascript
this.push(Buffer.concat([length, message]))
```

we should be doing this to avoid creating a new buffer:

```javascript
this.push(length);
this.push(message);
```

**Comment by rkusa** [comment]
Sounds good, would you like to create a PR for this change?

**Comment by davedoesdev** [comment]
Sure - will be a day or two. The existing tests should be okay?

**Comment by rkusa** [comment]
Thanks! You probably have to update the `test/prefixer.js`, because it will receive two chunks and not one

**Comment by davedoesdev** [comment]
This change makes my app run slower! The reason is it generates an extra network write. If I `cork` the socket stream it's piped to before doing writes to the frame stream and then `uncork` the socket stream afterwards then the performance is the unaffected.

So I don't think we can make this the default because in writing data you'd end up with an extra network packet than expected.

**Comment by davedoesdev** [comment]
However, if I do `cork` at a higher level in my app (where I know the level I want to batch things together) then I don't want the `Buffer.concat` in `Encoder.prototype._transform`.
@rkusa Do you think it would be OK to make this an option (with existing behaviour as default)?

**Comment by davedoesdev** [comment]
@rkusa I created a PR. It simply makes the existing behaviour overridable.
When I cork my destination stream at a higher-level in my app then I can override and push separately with no performance penalty (in fact corking across lots of writes is much faster).

**Comment by rkusa** [comment]
Thanks for the PR. It looks good! Just a small idea. Does setting the `highWaterMark` do something slightly higher than the bytes used for the length, improve your performance?

**Comment by davedoesdev** [comment]
My `highWaterMark` is set to 16384 and is enough to hold the length prefix and data. Node seems to call `writev` each time data is pushed to the piped destination. I was a bit surprised that it made a difference which is why I didn't want to bake any behaviour into `frame-stream`.

**Comment by rkusa** [comment]
Merged, thanks

**Comment by davedoesdev** [comment]
np, thanks again for this module

**Comment by davedoesdev** [comment]
Btw, would mind publishing v1.1.0 please? No urgency.

**Comment by rkusa** [comment]
Totally forgot that. It is published now :smile:
